      MODULE dsubrs_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      REAL(KIND(0.0D0)) FUNCTION dsubrs (EOL, I, J, JBLOCK)
      LOGICAL, INTENT(IN) :: EOL
      INTEGER, INTENT(IN) :: I
      INTEGER, INTENT(IN) :: J
      INTEGER :: JBLOCK
      END FUNCTION
      END INTERFACE
      END MODULE
