      MODULE engoutgg_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE ENGOUTGG(E,ILEV,NN,MODE)
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE), DIMENSION(NN), INTENT(IN) :: E
      INTEGER, DIMENSION(NN), INTENT(IN) :: ILEV
      INTEGER, INTENT(IN) :: NN
      INTEGER, INTENT(IN) :: MODE
      END SUBROUTINE
      END INTERFACE
      END MODULE
