      MODULE getoldmpi_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  15:25:01   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE getoldmpi (IDBLK)
      CHARACTER (LEN = 8), DIMENSION(*) :: IDBLK
      END SUBROUTINE
      END INTERFACE
      END MODULE
