      MODULE getscdmpi_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  15:26:24   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE getscdmpi (EOL, IDBLK, ISOFILE, RWFFILE)
      LOGICAL, INTENT(OUT) :: EOL
      CHARACTER (LEN = 8), DIMENSION(*) :: IDBLK
      CHARACTER (LEN = *) :: ISOFILE
      CHARACTER (LEN = *) :: RWFFILE
      END SUBROUTINE
      END INTERFACE
      END MODULE
