      MODULE newe_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE newe (J, SGN, NPRIME, MX, DELEPS, FAIL, INV)
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER, INTENT(IN) :: J
      REAL(DOUBLE), INTENT(IN) :: SGN
      INTEGER, INTENT(IN) :: NPRIME
      INTEGER, INTENT(IN) :: MX
      REAL(DOUBLE), INTENT(INOUT) :: DELEPS
      LOGICAL, INTENT(OUT) :: FAIL
      INTEGER, INTENT(OUT) :: INV
      END SUBROUTINE
      END INTERFACE
      END MODULE
