      MODULE orbout_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE orbout (RWFFILE2)
      CHARACTER (LEN = *), INTENT(IN) :: RWFFILE2
      END SUBROUTINE
      END INTERFACE
      END MODULE
