      MODULE setcof_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:21:02   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setcof (EOL, J)
      LOGICAL :: EOL
      INTEGER, INTENT(IN) :: J
      END SUBROUTINE
      END INTERFACE
      END MODULE
