      MODULE setham_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:23:52   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setham (JBLOCK, MYID, NPROCS, NCONTR_tot, NCONTR_tot2)
      USE vast_kind_param, ONLY: LONG
      INTEGER, INTENT(IN) :: JBLOCK
      INTEGER, INTENT(IN) :: MYID
      INTEGER, INTENT(IN) :: NPROCS
      INTEGER(LONG), DIMENSION(20) :: NCONTR_tot, NCONTR_tot2
      END SUBROUTINE
      END INTERFACE
      END MODULE
