      MODULE setmcp_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:27:31   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setmcp (NCORE, NBLKIN, IDBLK, FILEHEAD)
      INTEGER :: NCORE
      INTEGER, INTENT(IN) :: NBLKIN
      CHARACTER (LEN = 8), DIMENSION(*) :: IDBLK
      CHARACTER (LEN = *), INTENT(IN) :: FILEHEAD
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
