      MODULE setsum_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setsum (FILNAM)
      CHARACTER (LEN = *), INTENT(IN) :: FILNAM
      END SUBROUTINE
      END INTERFACE
      END MODULE
