      MODULE angdata_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE angdata (NAME, AVAIL, KAMAX) 
      CHARACTER (LEN = 24), INTENT(INOUT) :: NAME 
      LOGICAL, INTENT(OUT) :: AVAIL 
      INTEGER, INTENT(IN) :: KAMAX 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
