      MODULE gets_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE gets (S, NSHLI, NSHLF)
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE), DIMENSION(NSHLI,NSHLF), INTENT(OUT) :: S
      INTEGER, INTENT(IN) :: NSHLI
      INTEGER, INTENT(IN) :: NSHLF
      END SUBROUTINE
      END INTERFACE
      END MODULE
