      MODULE lodrwff_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:28:07   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE lodrwff (NAME, NTESTG)
      CHARACTER (LEN = 128), INTENT(IN) :: NAME
      INTEGER, INTENT(IN) :: NTESTG
      END SUBROUTINE
      END INTERFACE
      END MODULE
