      MODULE matml4_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE matml4 (C, A, B, NCROW, NCCOL, NAROW, NACOL, NBROW, NBCOL&
         , ITRNSP) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NCROW,NCCOL), INTENT(INOUT) :: C 
      REAL(DOUBLE), DIMENSION(NAROW,NACOL), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(NBROW,NBCOL), INTENT(IN) :: B 
      INTEGER, INTENT(IN) :: NCROW 
      INTEGER, INTENT(IN) :: NCCOL 
      INTEGER, INTENT(IN) :: NAROW 
      INTEGER, INTENT(IN) :: NACOL 
      INTEGER, INTENT(IN) :: NBROW 
      INTEGER, INTENT(IN) :: NBCOL 
      INTEGER, INTENT(IN) :: ITRNSP 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
