      MODULE prsym_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE prsym (A, MATDIM)
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE), DIMENSION(1), INTENT(IN) :: A
      INTEGER, INTENT(IN) :: MATDIM
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
