      MODULE qqsort_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:38:04   1/ 6/07  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE qqsort (NFILE, NUMBER, KSTART, NAME, KAMAX) 
      INTEGER, INTENT(IN) :: NFILE 
      INTEGER, INTENT(IN) :: NUMBER 
      INTEGER :: KSTART 
      CHARACTER (LEN = 24) :: NAME 
      INTEGER, INTENT(IN) :: KAMAX 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
