      MODULE radpar_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE radpar 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
