      MODULE setcslb_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06  
      SUBROUTINE setcslb (NAME, NCORE,IGG) 
      CHARACTER (LEN = 128), INTENT(IN) :: NAME 
      INTEGER :: NCORE,IGG
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
