      MODULE tiinig_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE tiinig (CIIN, NCSF, NCIV, I, L, CONST, CIOUT, NTESTG) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NCSF,NCIV), INTENT(IN) :: CIIN 
      INTEGER, INTENT(IN) :: NCSF 
      INTEGER, INTENT(IN) :: NCIV 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(IN) :: L 
      REAL(DOUBLE), INTENT(IN) :: CONST 
      REAL(DOUBLE), DIMENSION(NCSF,NCIV), INTENT(INOUT) :: CIOUT 
      INTEGER, INTENT(IN) :: NTESTG 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
