      MODULE vecsum_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE vecsum (C, A, B, FACA, FACB, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NDIM), INTENT(IN)  :: A
      REAL(DOUBLE), DIMENSION(NDIM), INTENT(IN)  :: B
      REAL(DOUBLE), DIMENSION(NDIM), INTENT(OUT) :: C
      REAL(DOUBLE), INTENT(IN) :: FACA 
      REAL(DOUBLE), INTENT(IN) :: FACB 
      INTEGER, INTENT(IN) :: NDIM 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
