      MODULE lval_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90 4.3E  21:49:59  11/14/01
      INTEGER FUNCTION lval (SYMBOL)
      CHARACTER (LEN = 1), INTENT(IN) :: SYMBOL
      END FUNCTION
      END INTERFACE
      END MODULE
