      MODULE bndinv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE bndinv (A, EL, N, DETERM, EPSIL, ITEST, NSIZE) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NSIZE,1), INTENT(INOUT) :: A 
      REAL(DOUBLE), DIMENSION(NSIZE,1), INTENT(INOUT) :: EL 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(OUT) :: DETERM 
      REAL(DOUBLE), INTENT(IN) :: EPSIL 
      INTEGER, INTENT(OUT) :: ITEST 
      INTEGER, INTENT(IN) :: NSIZE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
