      MODULE citrag_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE citrag (CIIN, NCSF, NCIV, L, NSHL, T, NIN, NTESTG, CIOUT, SCR) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NCSF,NCIV) :: CIIN 
      INTEGER, INTENT(IN) :: NCSF 
      INTEGER, INTENT(IN) :: NCIV 
      INTEGER, INTENT(IN) :: L 
      INTEGER, INTENT(IN) :: NSHL 
      REAL(DOUBLE), DIMENSION(NSHL,NSHL), INTENT(IN) :: T 
      INTEGER, INTENT(IN) :: NIN 
      INTEGER, INTENT(IN) :: NTESTG 
      REAL(DOUBLE), DIMENSION(NCSF,NCIV) :: CIOUT 
      REAL(DOUBLE), DIMENSION(NCSF,NCIV) :: SCR 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
