      MODULE getmix_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:21:54   1/ 6/07  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE getmix (NAME, INPCI, IBLK) 
      CHARACTER (LEN = 24), INTENT(IN) :: NAME 
      INTEGER, INTENT(IN) :: INPCI 
      INTEGER, INTENT(IN) :: IBLK 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
