      MODULE ifnmnx_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      INTEGER FUNCTION ifnmnx (IVEC, NEL, IMXMN)
      INTEGER, DIMENSION(NEL), INTENT(IN) :: IVEC
      INTEGER, INTENT(IN) :: NEL
      INTEGER, INTENT(IN) :: IMXMN
!...This routine performs I/O.
      END FUNCTION
      END INTERFACE
      END MODULE
