      MODULE inprod_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      REAL(KIND(0.0D0)) FUNCTION inprod (A, B, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: B 
      INTEGER, INTENT(IN) :: NDIM 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
