      MODULE intrpqi_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:26:14   1/ 6/07  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE intrpqi (PA, QA, MA, RA, J, DNORM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: PA 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: QA 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: RA 
      INTEGER, INTENT(IN) :: MA 
      INTEGER, INTENT(IN) :: J 
      REAL(DOUBLE), INTENT(OUT) :: DNORM 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
