      MODULE kapdata_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE kapdata (NTESTG, NCORE1, NCORE2) 
      INTEGER, INTENT(IN) :: NTESTG 
      INTEGER, INTENT(IN) :: NCORE1 
      INTEGER, INTENT(IN) :: NCORE2 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
