      MODULE ulla_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE ulla (A, U, L, NDIM, SCR)
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(IN) :: A
      REAL(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(OUT) :: U
      REAL(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(OUT) :: L
      INTEGER, INTENT(IN) :: NDIM
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: SCR
      END SUBROUTINE
      END INTERFACE
      END MODULE
