      MODULE wrtmat_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:25:32  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE wrtmat (A, NROW, NCOL, NMROW, NMCOL)
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE), DIMENSION(NMROW,NMCOL), INTENT(IN) :: A
      INTEGER, INTENT(IN) :: NROW
      INTEGER, INTENT(IN) :: NCOL
      INTEGER, INTENT(IN) :: NMROW
      INTEGER, INTENT(IN) :: NMCOL
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
