#!/bin/bash
# --------------------------------------------------------------------------------------
# GRASP2K ENVIRONMENT FLAGS
# --------------------------------------------------------------------------------------
#
# Define the following global variables according to your environment and
# source this script or add these definitions to your terminal configuration 
# file, eg. ~/.cshrc, ~/.bashrc or ~/.profile.
#
# Current version: Linux, gfortran gcc version 4.8.2
#
#
# Assumes ifort compiler on the path
# libraries invoked through a compiler option

# --------------------------------------------------------------------------------------
# Set up main flags
# --------------------------------------------------------------------------------------
export   FC=ifort                       # Fortran compiler 
export   FC_FLAGS="-O2 -save "          # Serial code compiler flags
#export  FC_FLAGS="-O0 -check all"      # Options for check for runtime errors
export   FC_LD="-mkl=sequential"        # Serial linker flags
export   LAPACK_LIB=" "                 # Library to be searched (not needed for ifort)
export   GRASP="${PWD}"                 # Location of the grasp2k root directory
# --------------------------------------------------------------------------------------
# Set up MPI related flags
# --------------------------------------------------------------------------------------
export   FC_MPI="mpifort"               # MPI
export   FC_MPIFLAGS="${FC_FLAGS}"      # Parallel code compiler flags
export   FC_MPILD="-mkl=sequential"     # Serical linker flags
# --------------------------------------------------------------------------------------
export MPI_TMP="/scratch/cff/case1"               # Location of directory for temporary files
