#!/bin/sh
set -x

#  6. Perform transition calculation for the n=6 CI results

n=6

#  First the biorthogonal transformations

mpirun -np 4 rbiotransform_mpi > out_rbiotransform <<EOF
y
y
oddCI$n
evenCI$n
y
EOF

# Then the transition calculations

mpirun -np 4 rtransition_mpi > out_transition <<EOF
y
y
oddCI$n
evenCI$n
E1
EOF
