      MODULE getinf_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  11:01:42   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE getinf
      END SUBROUTINE
      END INTERFACE
      END MODULE
