      MODULE outsdampi_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  11:01:42   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE outsdampi (LPRINT, NNONZ, NCF)
      LOGICAL, INTENT(IN) :: LPRINT
      INTEGER, INTENT(IN) :: NNONZ
      INTEGER, INTENT(IN) :: NCF
      END SUBROUTINE
      END INTERFACE
      END MODULE
