      MODULE setsum_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  13:54:22   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setsum (FULLNAME)
      CHARACTER (LEN = *), INTENT(IN) :: FULLNAME
      END SUBROUTINE
      END INTERFACE
      END MODULE
