      MODULE sort_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  13:24:58   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE sort (NFILE, NCOEFF, NTGRAL, LPRINT, NB, FHEAD)
      INTEGER, INTENT(IN)  :: NFILE
      INTEGER, INTENT(IN)  :: NCOEFF
      INTEGER, INTENT(OUT) :: NTGRAL
      LOGICAL, INTENT(IN)  :: LPRINT
      INTEGER, INTENT(IN)  :: NB
      CHARACTER (LEN = *), INTENT(IN) :: FHEAD
      END SUBROUTINE
      END INTERFACE
      END MODULE
