      MODULE getrmp_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  07:16:10   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE getrmp
      END SUBROUTINE
      END INTERFACE
      END MODULE
