      MODULE jqsr_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:22:09  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      INTEGER FUNCTION jqsr (IWHICH, ISUBSH, ICSF)
      INTEGER, INTENT(IN) :: IWHICH
      INTEGER, INTENT(IN) :: ISUBSH
      INTEGER, INTENT(IN) :: ICSF
      END FUNCTION
      END INTERFACE
      END MODULE
