      MODULE lodcslm_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  07:21:55   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE lodcslm (NCORE)
      INTEGER, INTENT(OUT) :: NCORE
      END SUBROUTINE
      END INTERFACE
      END MODULE
