      MODULE mctout_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  07:29:28   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE mctout (IOPAR, JKP, NAME)
      INTEGER, INTENT(OUT) :: IOPAR
      INTEGER, INTENT(IN) :: JKP
      CHARACTER (LEN = 24), DIMENSION(2) :: NAME
      END SUBROUTINE
      END INTERFACE
      END MODULE
