      MODULE densnew_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  18:42:57   1/ 6/07  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  11/02/17
      SUBROUTINE densnew (DINT1, DINT2, DINT3, DINT4, DINT5, DINT6) 
      USE vast_kind_param, ONLY: DOUBLE 
      USE parameter_def,   ONLY: NNNW
      REAL(DOUBLE), DIMENSION(NNNW,NNNW), INTENT(IN) :: DINT1 
      REAL(DOUBLE), DIMENSION(NNNW,NNNW), INTENT(IN) :: DINT2 
      REAL(DOUBLE), DIMENSION(NNNW,NNNW), INTENT(IN) :: DINT3 
      REAL(DOUBLE), DIMENSION(NNNW,NNNW), INTENT(IN) :: DINT4 
      REAL(DOUBLE), DIMENSION(NNNW,NNNW), INTENT(IN) :: DINT5 
      REAL(DOUBLE), DIMENSION(NNNW,NNNW), INTENT(IN) :: DINT6 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
