      MODULE polint_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:40:03  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  11/02/17
      SUBROUTINE polint (XA, YA, N, X, Y, DY) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: XA 
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: YA 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(IN) :: X 
      REAL(DOUBLE), INTENT(OUT) :: Y 
      REAL(DOUBLE), INTENT(OUT) :: DY 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
