      MODULE sms_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  18:46:30   1/ 6/07  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  11/02/17
      SUBROUTINE sms 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
