      MODULE wghtd5_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  08:39:50   2/21/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  11/02/17
      SUBROUTINE wghtd5 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
