      MODULE brintf_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      REAL(KIND(0.0D0)) FUNCTION brintf (ITYPE, IA, IB, IC, ID, K)
      INTEGER, INTENT(IN) :: ITYPE
      INTEGER, INTENT(IN) :: IA
      INTEGER, INTENT(IN) :: IB
      INTEGER, INTENT(IN) :: IC
      INTEGER, INTENT(IN) :: ID
      INTEGER, INTENT(IN) :: K
      END FUNCTION
      END INTERFACE
      END MODULE
