      MODULE dnicmv_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE dnicmv (N, M, B, C)
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER, INTENT(IN) :: N
      INTEGER, INTENT(IN) :: M
      REAL(DOUBLE), DIMENSION(N,M), INTENT(IN) :: B
      REAL(DOUBLE), DIMENSION(N,M), INTENT(INOUT) :: C
      END SUBROUTINE
      END INTERFACE
      END MODULE
