      MODULE funk_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      REAL(KIND(0.0D0)) FUNCTION funk (X, N)
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE), INTENT(IN) :: X
      INTEGER, INTENT(IN) :: N
!...This routine performs I/O.
      END FUNCTION
      END INTERFACE
      END MODULE
