      MODULE genintrkwrap_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:35:13  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE genintrkwrap (MYID, NPROCS, J2MAX)
      INTEGER :: MYID
      INTEGER :: NPROCS
      INTEGER :: J2MAX
      END SUBROUTINE
      END INTERFACE
      END MODULE
