      MODULE genmat_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE genmat (ATWINV, JBLOCK, MYID, NPROCS, ELSTO, IRESTART, SLF_EN)
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE) :: ATWINV
      INTEGER, INTENT(IN) :: JBLOCK
      INTEGER, INTENT(IN) :: MYID
      INTEGER, INTENT(IN) :: NPROCS
      REAL(DOUBLE), INTENT(OUT) :: ELSTO
      INTEGER, INTENT(OUT) :: IRESTART
      REAL(DOUBLE), DIMENSION(*) :: SLF_EN
      END SUBROUTINE
      END INTERFACE
      END MODULE
