      MODULE indtpi_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      INTEGER FUNCTION indtpi (ITYPE, I)
      INTEGER, INTENT(IN) :: ITYPE
      INTEGER :: I
      END FUNCTION
      END INTERFACE
      END MODULE
