      MODULE maneig_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:07:38   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE maneig (IATJPO, IASPAR, NELMNT_a)
      USE vast_kind_param, ONLY: LONG
      INTEGER, INTENT(OUT) :: IATJPO
      INTEGER, INTENT(OUT) :: IASPAR
      INTEGER(LONG)        :: NELMNT_a
      END SUBROUTINE
      END INTERFACE
      END MODULE
