      MODULE hfszeeman_I 
      INTERFACE
!...Generated by Wenxian Li  12/28/18   
      SUBROUTINE HFSZEEMAN (NOFFD)
      INTEGER, INTENT(IN) :: NOFFD
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
