      MODULE matelt_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:36:34  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  11/01/17
      SUBROUTINE matelt (I1, K, I2, APART, GJPART, DGJPART) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: I1 
      INTEGER, INTENT(IN) :: K 
      INTEGER, INTENT(IN) :: I2 
      REAL(DOUBLE), INTENT(OUT) :: APART 
      REAL(DOUBLE), INTENT(OUT) :: GJPART 
      REAL(DOUBLE), INTENT(OUT) :: DGJPART 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
