      MODULE setsum_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:36:34  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  11/01/17
!...Modified by Wenxian Li 12/28/18
      SUBROUTINE setsum (NAME, NCI, NOFFD) 
      CHARACTER (LEN = 24), INTENT(IN) :: NAME 
      INTEGER, INTENT(IN) :: NCI 
      INTEGER, INTENT(IN) :: NOFFD 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
