      MODULE strsum_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:36:34  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  11/01/17
      SUBROUTINE strsum 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
