      MODULE rintdens_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:40:03  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  11/02/17
      REAL(KIND(0.0D0)) FUNCTION rintdens (I, J)
      INTEGER :: I
      INTEGER :: J
      END FUNCTION
      END INTERFACE
      END MODULE
