      MODULE dampck_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE dampck (IPR, J, ED1, ED2)
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER, INTENT(INOUT) :: IPR
      INTEGER, INTENT(IN) :: J
      REAL(DOUBLE), INTENT(INOUT) :: ED1
      REAL(DOUBLE), INTENT(INOUT) :: ED2
      END SUBROUTINE
      END INTERFACE
      END MODULE
