      MODULE getaldwt_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE getaldwt (NCF, WT)
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER, INTENT(IN) :: NCF
      REAL(DOUBLE), DIMENSION(NCF), INTENT(INOUT) :: WT
      END SUBROUTINE
      END INTERFACE
      END MODULE
