      MODULE rmcdhf_mem_C
!   Written by  G. Gaigalas               Vilnius, September 2021  *
      USE vast_kind_param, ONLY:  DOUBLE, LONG
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_31
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_32
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_33
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_34
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_35
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_36
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_37
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_38
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_39
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_40
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_41
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_42
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_43
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_44
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_45
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_46
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_47
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_48
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_49
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF_50
      REAL(DOUBLE), DIMENSION(:), POINTER :: COEFF
      INTEGER, DIMENSION(:), pointer ::IMIN1_30, IMAX1_30
      INTEGER, DIMENSION(:), pointer ::IMIN2_30, IMAX2_30
      INTEGER, DIMENSION(:), pointer ::INDX, ICLMN
      INTEGER, DIMENSION(:), pointer ::IENDC_30, IROW_30
      INTEGER, DIMENSION(:), pointer ::LAB_31,NCONTR_31,ICLMN_31,INDX_31
      INTEGER, DIMENSION(:), pointer ::LAB_32,NCONTR_32,ICLMN_32,INDX_32
      INTEGER, DIMENSION(:), pointer ::LAB_33,NCONTR_33,ICLMN_33,INDX_33
      INTEGER, DIMENSION(:), pointer ::LAB_34,NCONTR_34,ICLMN_34,INDX_34
      INTEGER, DIMENSION(:), pointer ::LAB_35,NCONTR_35,ICLMN_35,INDX_35
      INTEGER, DIMENSION(:), pointer ::LAB_36,NCONTR_36,ICLMN_36,INDX_36
      INTEGER, DIMENSION(:), pointer ::LAB_37,NCONTR_37,ICLMN_37,INDX_37
      INTEGER, DIMENSION(:), pointer ::LAB_38,NCONTR_38,ICLMN_38,INDX_38
      INTEGER, DIMENSION(:), pointer ::LAB_39,NCONTR_39,ICLMN_39,INDX_39
      INTEGER, DIMENSION(:), pointer ::LAB_40,NCONTR_40,ICLMN_40,INDX_40
      INTEGER, DIMENSION(:), pointer ::LAB_41,NCONTR_41,ICLMN_41,INDX_41
      INTEGER, DIMENSION(:), pointer ::LAB_42,NCONTR_42,ICLMN_42,INDX_42
      INTEGER, DIMENSION(:), pointer ::LAB_43,NCONTR_43,ICLMN_43,INDX_43
      INTEGER, DIMENSION(:), pointer ::LAB_44,NCONTR_44,ICLMN_44,INDX_44
      INTEGER, DIMENSION(:), pointer ::LAB_45,NCONTR_45,ICLMN_45,INDX_45
      INTEGER, DIMENSION(:), pointer ::LAB_46,NCONTR_46,ICLMN_46,INDX_46
      INTEGER, DIMENSION(:), pointer ::LAB_47,NCONTR_47,ICLMN_47,INDX_47
      INTEGER, DIMENSION(:), pointer ::LAB_48,NCONTR_48,ICLMN_48,INDX_48
      INTEGER, DIMENSION(:), pointer ::LAB_49,NCONTR_49,ICLMN_49,INDX_49
      INTEGER, DIMENSION(:), pointer ::LAB_50,NCONTR_50,ICLMN_50,INDX_50
      END MODULE rmcdhf_mem_C
