      MODULE fivefirst_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06  
      SUBROUTINE fivefirst (SLUT1, SLUT2, POSN, POSL) 
      logical, INTENT(INOUT) :: SLUT1 
      logical, INTENT(INOUT) :: SLUT2 
      integer, DIMENSION(110), INTENT(IN) :: POSN 
      integer, DIMENSION(110), INTENT(IN) :: POSL 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
