      MODULE kopp1_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      SUBROUTINE kopp1 (POS, RAD2, J, S, ANTKO)
      integer, INTENT(IN) :: POS
      character (LEN = 200), INTENT(OUT) :: RAD2
      integer, DIMENSION(20), INTENT(IN) :: J
      integer, DIMENSION(20), INTENT(IN) :: S
      integer, DIMENSION(20), INTENT(IN) :: ANTKO
      END SUBROUTINE
      END INTERFACE
      END MODULE
