      MODULE lockad_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      SUBROUTINE lockad (CLOSED, MED, SLUT, EXPAND)
      logical, DIMENSION(15,0:10), INTENT(OUT) :: CLOSED
      logical, DIMENSION(15,0:10), INTENT(OUT) :: MED
      logical, INTENT(OUT) :: SLUT
      logical, INTENT(IN) :: EXPAND
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
