      MODULE matcin_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      SUBROUTINE matcin (LOCK, CLOSED, MED, VARMAX, CFMAX, NMAX, MINJ, MAXJ&
         , LIM)
      logical, DIMENSION(15,0:10), INTENT(OUT) :: LOCK
      logical, DIMENSION(15,0:10), INTENT(IN) :: CLOSED
      logical, DIMENSION(15,0:10), INTENT(IN) :: MED
      integer, INTENT(IN) :: VARMAX
      integer, INTENT(IN) :: CFMAX
      integer, INTENT(OUT) :: NMAX
      integer, INTENT(IN) :: MINJ
      integer, INTENT(IN) :: MAXJ
      integer, DIMENSION(15), INTENT(INOUT) :: LIM
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
