      MODULE merge_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06  
      SUBROUTINE merge (SINGLE, POSN, POSL, II) 
      logical, INTENT(IN) :: SINGLE 
      integer, DIMENSION(110) :: POSN 
      integer, DIMENSION(110) :: POSL 
      integer, INTENT(IN) :: II 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
