      MODULE open79_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      SUBROUTINE open79 (I)
      integer, INTENT(IN) :: I
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
