      MODULE reffa_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      SUBROUTINE reffa (POSN, POSL)
      integer, DIMENSION(110), INTENT(INOUT) :: POSN
      integer, DIMENSION(110), INTENT(INOUT) :: POSL
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
