      MODULE test_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      SUBROUTINE test (P1, P2, POP1, POP2, NMAX)
      logical, INTENT(OUT) :: P1
      logical, INTENT(OUT) :: P2
      integer, DIMENSION(15,0:10,0:1), INTENT(IN) :: POP1
      integer, DIMENSION(15,0:10,0:1), INTENT(IN) :: POP2
      integer, INTENT(IN) :: NMAX
      END SUBROUTINE
      END INTERFACE
      END MODULE
