      MODULE blandc_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06  
      SUBROUTINE blandc (VARMAX, CFMAX, LOCK, MED, MINJ, MAXJ, NMAX, POSN, POSL&
         , LIM) 
      integer :: VARMAX 
      integer, INTENT(IN) :: CFMAX 
      logical, DIMENSION(15,0:10), INTENT(IN) :: LOCK 
      logical, DIMENSION(15,0:10), INTENT(IN) :: MED 
      integer :: MINJ 
      integer :: MAXJ 
      integer, INTENT(IN) :: NMAX 
      integer, DIMENSION(110), INTENT(IN) :: POSN 
      integer, DIMENSION(110), INTENT(IN) :: POSL 
      integer, DIMENSION(15) :: LIM 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
