      MODULE blandb_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      SUBROUTINE blandb (ORG, NMAX, VARMAX, LOCK, FIL, LOW, LIM, POSN, POSL&
         , MINJ, MAXJ)
      integer, DIMENSION(15,0:10), INTENT(INOUT) :: ORG
      integer, INTENT(IN) :: NMAX
      integer :: VARMAX
      logical, DIMENSION(15,0:10) :: LOCK
      integer, INTENT(IN) :: FIL
      integer, DIMENSION(15,0:10) :: LOW
      integer, DIMENSION(15), INTENT(IN) :: LIM
      integer, DIMENSION(110) :: POSN
      integer, DIMENSION(110) :: POSL
      integer :: MINJ
      integer :: MAXJ
      END SUBROUTINE
      END INTERFACE
      END MODULE
