      MODULE copy7t9_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      SUBROUTINE copy7t9
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
