      MODULE fivelines_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      SUBROUTINE fivelines (ORG, LOCKED, CLOSED, FIRST, POSN, POSL)
      integer, DIMENSION(15,0:10), INTENT(INOUT) :: ORG
      logical, DIMENSION(15,0:10), INTENT(IN) :: LOCKED
      logical, DIMENSION(15,0:10), INTENT(IN) :: CLOSED
      logical, INTENT(IN) :: FIRST
      integer, DIMENSION(110), INTENT(IN) :: POSN
      integer, DIMENSION(110), INTENT(IN) :: POSL
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
