      MODULE kopp2_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      SUBROUTINE kopp2 (POS, RAD3, J, JPRIM, PAR, ANTKO)
      integer, INTENT(IN) :: POS
      character (LEN = 200), INTENT(OUT) :: RAD3
      integer, DIMENSION(20), INTENT(IN) :: J
      integer, DIMENSION(20), INTENT(IN) :: JPRIM
      integer, INTENT(IN) :: PAR
      integer, DIMENSION(20), INTENT(IN) :: ANTKO
      END SUBROUTINE
      END INTERFACE
      END MODULE
