      MODULE lika_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      LOGICAL FUNCTION lika (POP0, POP1)
      integer, DIMENSION(15,0:10,0:1), INTENT(IN) :: POP0
      integer, DIMENSION(15,0:10,0:1), INTENT(IN) :: POP1
      END FUNCTION
      END INTERFACE
      END MODULE
