      MODULE matbin_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      SUBROUTINE matbin (ORG, LOCK, CLOSED, VARMAX, SKAL, SECOND, ANEL0, PAR0&
         , LOW, NMAX, LIM, DUBBEL, MINJ, MAXJ)
      integer, DIMENSION(15,0:10), INTENT(INOUT) :: ORG
      logical, DIMENSION(15,0:10), INTENT(INOUT) :: LOCK
      logical, DIMENSION(15,0:10), INTENT(INOUT) :: CLOSED
      integer, INTENT(IN) :: VARMAX
      integer, INTENT(OUT) :: SKAL
      logical, INTENT(INOUT) :: SECOND
      integer, INTENT(IN) :: ANEL0
      integer, INTENT(OUT) :: PAR0
      integer, DIMENSION(15,0:10), INTENT(INOUT) :: LOW
      integer, INTENT(OUT) :: NMAX
      integer, DIMENSION(15), INTENT(INOUT) :: LIM
      logical, DIMENSION(15,0:10), INTENT(OUT) :: DUBBEL
      integer, INTENT(IN) :: MINJ
      integer, INTENT(IN) :: MAXJ
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
