      MODULE mergeb_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06
      SUBROUTINE mergeb (ANTAL)
      integer, INTENT(OUT) :: ANTAL
      END SUBROUTINE
      END INTERFACE
      END MODULE
