      MODULE reada_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:44:54  12/27/06  
      SUBROUTINE reada (RAD1, POP, SKAL, SLUT) 
      character (LEN = 200), INTENT(IN) :: RAD1 
      integer, DIMENSION(15,0:10,0:1), INTENT(OUT) :: POP 
      integer, INTENT(INOUT) :: SKAL 
      logical, INTENT(OUT) :: SLUT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
