      MODULE getmixblock_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  18:32:57   1/ 6/07  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  11/01/17
      SUBROUTINE getmixblock (NAME, NCI) 
      CHARACTER (LEN = 24), INTENT(IN) :: NAME 
      INTEGER, INTENT(IN) :: NCI 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
