      MODULE el1INT_I
      INTERFACE
!
      SUBROUTINE EL1INT(JJA,JJB,JA,JB,IIRE,ICOLBREI,INTERACT)
      INTEGER, INTENT(IN) :: JJA,JJB,JA,JB,IIRE,ICOLBREI
      INTEGER, INTENT(OUT) :: INTERACT
      END SUBROUTINE
      END INTERFACE
      END MODULE
