      MODULE el32INT_I
      INTERFACE
!
      SUBROUTINE EL32INT(JJJA,JJJB,JA,JB,JJA,JJB,JJC,JJD,ICOLBREI,     &
                                                               INTERACT)
      INTEGER, INTENT(IN) :: JJJA,JJJB,JA,JB,JJA,JJB,JJC,JJD,ICOLBREI
      INTEGER, INTENT(OUT) :: INTERACT
      END SUBROUTINE
      END INTERFACE
      END MODULE
