      MODULE el3INT_I
      INTERFACE
!
      SUBROUTINE EL3INT(JJA,JJB,JA,JB,JC,JD,ICOLBREI,INTERACT)
      INTEGER, INTENT(IN) :: JJA,JJB,JA,JB,JC,JD,ICOLBREI
      INTEGER, INTENT(OUT) :: INTERACT
      END SUBROUTINE
      END INTERFACE
      END MODULE
