      MODULE el51INT_I
      INTERFACE
!
      SUBROUTINE EL51INT(JJA,JJB,JA,JB,JC,JD,IREZ,ICOLBREI,INTERACT)
      INTEGER, INTENT(IN) :: JJA,JJB,JA,JB,JC,JD,IREZ,ICOLBREI
      INTEGER, INTENT(OUT) :: INTERACT
      END SUBROUTINE
      END INTERFACE
      END MODULE
