      MODULE el52_I
      INTERFACE
!
      SUBROUTINE EL52(JJA,JJB,JA,JB,JC,JD,IREZ,ICOLBREI)
      INTEGER, INTENT(IN) :: JJA,JJB,JA,JB,JC,JD,IREZ,ICOLBREI
      END SUBROUTINE
      END INTERFACE
      END MODULE
