      MODULE Interact_MR_I
      INTERFACE
      SUBROUTINE Interact_MR(ICOLBREI,I_Count)
      INTEGER, INTENT(IN) :: ICOLBREI
      INTEGER, INTENT(INOUT) :: I_Count
      END SUBROUTINE
      END INTERFACE
      END MODULE
