      MODULE lodcsl_MR_I
      INTERFACE
      SUBROUTINE lodcsl_MR (NCORE,NPEEL,NCFD,NEXT_BLOCK)
      INTEGER, INTENT(IN) :: NCORE
      INTEGER, INTENT(INOUT) :: NPEEL
      INTEGER, INTENT(OUT)   :: NCFD
      LOGICAL, INTENT(OUT)  :: NEXT_BLOCK
      END SUBROUTINE
      END INTERFACE
      END MODULE
