      MODULE onescalar1INT_I
      INTERFACE
!
      SUBROUTINE ONESCALAR1INT(NS,JJA,JJB,JA,JB,INTERACT)
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER, INTENT(IN) :: NS,JJA,JJB,JA,JB
      INTEGER, INTENT(OUT) :: INTERACT
      END SUBROUTINE
      END INTERFACE
      END MODULE
