      MODULE onescalarINT_I
      INTERFACE
!
      SUBROUTINE ONESCALARINT(JA,JB,IA1,IA2,INTERACT)
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER, INTENT(IN)  :: JA,JB
      INTEGER, INTENT(OUT) :: IA1,IA2
      INTEGER, INTENT(OUT) :: INTERACT
      END SUBROUTINE
      END INTERFACE
      END MODULE
