      MODULE onescalar2INT_I
      INTERFACE
!
      SUBROUTINE ONESCALAR2INT(JJA,JJB,JA,JB,INTERACT)
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER, INTENT(IN) :: JJA,JJB,JA,JB
      INTEGER, INTENT(OUT) :: INTERACT
      END SUBROUTINE
      END INTERFACE
      END MODULE
