      MODULE set_CSF_list_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:49:50  12/27/06
      SUBROUTINE set_CSF_list (NCORE,NPEEL)
      INTEGER,  INTENT(OUT) :: NCORE,NPEEL
      END SUBROUTINE
      END INTERFACE
      END MODULE
