      MODULE bessel_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE bessel (IA, IB, IK, IW, K)
      INTEGER, INTENT(IN) :: IA
      INTEGER, INTENT(IN) :: IB
      INTEGER, INTENT(IN) :: IK
      INTEGER, INTENT(IN) :: IW
      INTEGER, INTENT(IN) :: K
      END SUBROUTINE
      END INTERFACE
      END MODULE
