      MODULE breid_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE breid (JA, JB, JA1, IPCA, JB1)
      INTEGER, INTENT(IN) :: JA
      INTEGER, INTENT(IN) :: JB
      INTEGER, INTENT(IN) :: JA1
      INTEGER, INTENT(IN) :: IPCA
      INTEGER, INTENT(IN) :: JB1
      END SUBROUTINE
      END INTERFACE
      END MODULE
