      MODULE dmerge_dnicmv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE dmerge_dnicmv (N, DB, DC, DA, DCONST, DL) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: DB 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: DC 
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: DA 
      REAL(DOUBLE), INTENT(IN) :: DCONST 
      REAL(DOUBLE), INTENT(OUT) :: DL 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
