      MODULE genmat2_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE genmat2 (IRESTART, NELMNT_A, ELSTO)
      USE vast_kind_param,    ONLY: DOUBLE, LONG
      INTEGER, INTENT(IN)        :: IRESTART
      INTEGER(LONG), INTENT(OUT) :: NELMNT_A
      REAL(DOUBLE), INTENT(IN)   :: ELSTO
      END SUBROUTINE
      END INTERFACE
      END MODULE
