      MODULE maneig_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:07:38   1/ 5/07  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE maneig (IATJPO, IASPAR) 
      INTEGER, INTENT(OUT) :: IATJPO 
      INTEGER, INTENT(OUT) :: IASPAR 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
