      MODULE mohr_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE mohr (N, KAPPA, Z, FZALFA)
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER NUMVAL
      PARAMETER (NUMVAL = 12)
      INTEGER, INTENT(IN) :: N
      INTEGER, INTENT(IN) :: KAPPA
      REAL(DOUBLE) :: Z
      REAL(DOUBLE), INTENT(OUT) :: FZALFA
      END SUBROUTINE
      END INTERFACE
      END MODULE
