      MODULE qed_slfen_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE qed_slfen (SLFINT)
      USE vast_kind_param, ONLY: DOUBLE
      USE parameter_def,   ONLY: NNNW
      REAL(DOUBLE), DIMENSION(NNNW), INTENT(OUT) :: SLFINT
      END SUBROUTINE
      END INTERFACE
      END MODULE
