      MODULE setcsl_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setcsl (NAME, NCORE, NBLKIN, IDBLK)
      CHARACTER (LEN = *) :: NAME
      INTEGER :: NCORE
      INTEGER, INTENT(IN) :: NBLKIN
      CHARACTER (LEN = 8), DIMENSION(*) :: IDBLK
      END SUBROUTINE
      END INTERFACE
      END MODULE
