      MODULE triangrk_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      LOGICAL FUNCTION triangrk (LA, K, LB)
      INTEGER, INTENT(IN) :: LA
      INTEGER, INTENT(IN) :: K
      INTEGER, INTENT(IN) :: LB
      END FUNCTION
      END INTERFACE
      END MODULE
