      MODULE zkf_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE zkf (K, I, J) 
      INTEGER, INTENT(IN) :: K 
      INTEGER :: I 
!VAST...Dummy argument I is not referenced in this routine.
      INTEGER :: J 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
