      MODULE gco_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      REAL(KIND(0.0D0)) FUNCTION gco (K, IR, IA, IB)
      INTEGER :: K
      INTEGER :: IR
      INTEGER, INTENT(IN) :: IA
      INTEGER, INTENT(IN) :: IB
      END FUNCTION
      END INTERFACE
      END MODULE
