      MODULE getoldwt_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE getoldwt (NDEF, NCMIN, WT)
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER :: NDEF
!VAST...Dummy argument NDEF is not referenced in this routine.
      INTEGER, INTENT(IN) :: NCMIN
      REAL(DOUBLE), DIMENSION(NCMIN), INTENT(INOUT) :: WT
      END SUBROUTINE
      END INTERFACE
      END MODULE
