      MODULE in_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE in (IORB, JP, P, Q, MTP)
      USE vast_kind_param,  ONLY: DOUBLE
      USE parameter_def,    ONLY: NNNP
      integer, INTENT(IN) :: IORB
      integer, INTENT(IN) :: JP
      real(DOUBLE), DIMENSION(NNNP), INTENT(INOUT) :: P
      real(DOUBLE), DIMENSION(NNNP), INTENT(INOUT) :: Q
      integer, INTENT(OUT) :: MTP
      END SUBROUTINE
      END INTERFACE
      END MODULE
