      MODULE newcompi_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  16:53:04   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE newcompi (SUM)
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE), INTENT(OUT) :: SUM
      END SUBROUTINE
      END INTERFACE
      END MODULE
