      MODULE scfmpi_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:16:00   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE scfmpi (EOL, RWFFILE2)
      LOGICAL, INTENT(IN) :: EOL
      CHARACTER (LEN = *) :: RWFFILE2
      END SUBROUTINE
      END INTERFACE
      END MODULE
