      MODULE setcslmpi_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setcslmpi (NAME, NCORE, IDBLK)
      CHARACTER (LEN = *), INTENT(IN) :: NAME
      INTEGER :: NCORE
      CHARACTER (LEN = 8), DIMENSION(*) :: IDBLK
!VAST...Dummy argument IDBLK is not referenced in this routine.
      END SUBROUTINE
      END INTERFACE
      END MODULE
