      MODULE setdbgmpi_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:22:29   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setdbgmpi (DBGFILE)
      CHARACTER (LEN = *), INTENT(IN) :: DBGFILE
      END SUBROUTINE
      END INTERFACE
      END MODULE
