      MODULE setlagmpi_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:25:08   1/ 5/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setlagmpi (EOL)
      LOGICAL :: EOL
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
