      MODULE xpot_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  16:59:40   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE xpot (J)
      INTEGER, INTENT(IN) :: J
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
