      MODULE hfsgg_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  18:34:47   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  11/01/17
      SUBROUTINE hfsgg
      END SUBROUTINE
      END INTERFACE
      END MODULE
