      MODULE rinthf_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:36:34  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  11/01/17
      REAL(KIND(0.0D0)) FUNCTION rinthf (I, J, K) 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(IN) :: J 
      INTEGER, INTENT(IN) :: K 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
