      MODULE multbc_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE multbc (N, K, M, C, TEMP, B)
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER, INTENT(IN) :: N
      INTEGER, INTENT(IN) :: K
      INTEGER, INTENT(IN) :: M
      REAL(DOUBLE), DIMENSION(K*M) :: C
      REAL(DOUBLE), DIMENSION(M) :: TEMP
      REAL(DOUBLE), DIMENSION(N*K) :: B
!VAST...Calls: DGEMV, DCOPY
      END SUBROUTINE
      END INTERFACE
      END MODULE
