      MODULE dracah_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  07:27:24   2/14/04
      SUBROUTINE dracah (I, J, K, L, M, N, RAC)
      USE vast_kind_param, ONLY: DOUBLE
      INTEGER MFACT
      PARAMETER (MFACT = 500)
      INTEGER, INTENT(IN) :: I
      INTEGER, INTENT(IN) :: J
      INTEGER, INTENT(IN) :: K
      INTEGER, INTENT(IN) :: L
      INTEGER, INTENT(IN) :: M
      INTEGER, INTENT(IN) :: N
      REAL(DOUBLE), INTENT(OUT) :: RAC
!VAST.../FACTS/ GAM(IN)
      END SUBROUTINE
      END INTERFACE
      END MODULE
