      MODULE el1_I
      INTERFACE
!
      SUBROUTINE EL1(JJA,JJB,JA,JB,IIRE,ICOLBREI)
      INTEGER, INTENT(IN) :: JJA,JJB,JA,JB,IIRE,ICOLBREI
      END SUBROUTINE
      END INTERFACE
      END MODULE
