      MODULE el31_I
      INTERFACE
!
      SUBROUTINE EL31(JJJA,JJJB,JA,JB,JJA,JJB,JJC,JJD,ICOLBREI)
      INTEGER, INTENT(IN) :: JJJA,JJJB,JA,JB,JJA,JJB,JJC,JJD,ICOLBREI
      END SUBROUTINE
      END INTERFACE
      END MODULE
