      MODULE el32_I
      INTERFACE
!
      SUBROUTINE EL32(JJJA,JJJB,JA,JB,JJA,JJB,JJC,JJD,ICOLBREI)
      INTEGER, INTENT(IN) :: JJJA,JJJB,JA,JB,JJA,JJB,JJC,JJD,ICOLBREI
      END SUBROUTINE
      END INTERFACE
      END MODULE
