      MODULE el3_I
      INTERFACE
!
      SUBROUTINE EL3(JJA,JJB,JA,JB,JC,JD,ICOLBREI)
      INTEGER, INTENT(IN) :: JJA,JJB,JA,JB,JC,JD,ICOLBREI
      END SUBROUTINE
      END INTERFACE
      END MODULE
