      MODULE el5_I
      INTERFACE
!
      SUBROUTINE EL5(JJA,JJB,JA,JB,JC,JD,ICOLBREI)
      INTEGER, INTENT(IN) :: JJA,JJB,JA,JB,JC,JD,ICOLBREI
      END SUBROUTINE
      END INTERFACE
      END MODULE
