      MODULE GG1233_I
      INTERFACE
!
      SUBROUTINE GG1233(IK1,IK2,IK3,BK1,BK2,BK3,ID1,ID2,ID3,BD1,  &
      BD2,BD3,K1,QM1,QM2,QM3,QM4,WW)
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER,      INTENT(IN)               :: K1
      INTEGER,      INTENT(IN), DIMENSION(7) :: IK1,IK2,IK3,ID1,ID2,ID3
      REAL(DOUBLE), INTENT(IN)               :: QM1,QM2,QM3,QM4
      REAL(DOUBLE), INTENT(IN), DIMENSION(3) :: BK1,BK2,BK3,BD1,BD2,BD3
      REAL(DOUBLE), INTENT(OUT)              :: WW
      END SUBROUTINE
      END INTERFACE
      END MODULE
