      MODULE gracah1_I
      INTERFACE
!
      SUBROUTINE GRACAH1(I,J,K,L,M,N,RAC)
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER MFACT
      PARAMETER (MFACT = 500)
      INTEGER , INTENT(IN) :: I
      INTEGER , INTENT(IN) :: J
      INTEGER , INTENT(IN) :: K
      INTEGER , INTENT(IN) :: L
      INTEGER , INTENT(IN) :: M
      INTEGER , INTENT(IN) :: N
      REAL(DOUBLE) , INTENT(OUT) :: RAC
      END SUBROUTINE
      END INTERFACE
      END MODULE
