      MODULE itrexg_I
      INTERFACE
!
      INTEGER FUNCTION ITREXG(I1,I2,I3,I4,K)
      INTEGER, INTENT(IN)  :: I1, I2, I3, I4
      INTEGER, INTENT(OUT) :: K
      END FUNCTION
      END INTERFACE
      END MODULE
