      MODULE ittk_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90 4.3E  09:56:17  11/16/01
      INTEGER FUNCTION ittk (I, J, K)
      INTEGER, INTENT(IN) :: I
      INTEGER, INTENT(IN) :: J
      INTEGER, INTENT(IN) :: K
      END FUNCTION
      END INTERFACE
      END MODULE
