      MODULE ixjtik_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90 4.3E  10:05:49  11/16/01
      INTEGER FUNCTION ixjtik (I, J, K, L, M, N)
      INTEGER :: I
      INTEGER :: J
      INTEGER :: K
      INTEGER :: L
      INTEGER :: M
      INTEGER :: N
!VAST...Calls: ITTK
      END FUNCTION
      END INTERFACE
      END MODULE
