      MODULE oneparticlejj1_I
      INTERFACE
!
      SUBROUTINE ONEPARTICLEJJ1(NS,KA,JJA,JJB,JA,JB,COEFF)
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER, INTENT(IN) :: NS,KA,JJA,JJB,JA,JB
      REAL(DOUBLE), INTENT(OUT) :: COEFF
      END SUBROUTINE
      END INTERFACE
      END MODULE
