      MODULE oneparticlejj2_I
      INTERFACE
!
      SUBROUTINE ONEPARTICLEJJ2(NS,KA,JA,JB,COEFF)
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER, INTENT(IN) :: NS,KA,JA,JB
      REAL(DOUBLE), INTENT(OUT) :: COEFF
      END SUBROUTINE
      END INTERFACE
      END MODULE
