      MODULE onescalar2_I
      INTERFACE
!
      SUBROUTINE ONESCALAR2(JJA,JJB,JA,JB,COEFF)
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER, INTENT(IN) :: JJA,JJB,JA,JB
      REAL(DOUBLE), INTENT(OUT) :: COEFF
      END SUBROUTINE
      END INTERFACE
      END MODULE
