      MODULE onescalar1_I
      INTERFACE
!
      SUBROUTINE ONESCALAR1(NS,JJA,JJB,JA,JB,COEFF)
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER, INTENT(IN) :: NS,JJA,JJB,JA,JB
      REAL(DOUBLE), INTENT(OUT) :: COEFF
      END SUBROUTINE
      END INTERFACE
      END MODULE
