      MODULE rec3_I
      INTERFACE
!
      SUBROUTINE REC3(JA1,JA2,JA3,K1,K2,K3,IRE,IAT,RECC)
      USE vast_kind_param,  ONLY:  DOUBLE
      INTEGER, INTENT(IN)       :: JA1,JA2,JA3,K1,K2,K3,IRE
      INTEGER, INTENT(OUT)      :: IAT
      REAL(DOUBLE), INTENT(OUT) :: RECC
      END SUBROUTINE
      END INTERFACE
      END MODULE
