      MODULE reco4_I
      INTERFACE
!
      SUBROUTINE RECO4(JA1,JA2,JA3,JA4,K1,K2,K3,K4,KA,IRE,IAT,RECC)
      USE vast_kind_param,  ONLY:  DOUBLE
      INTEGER, INTENT(IN)       :: JA1,JA2,JA3,JA4,K1,K2,K3,K4,KA,IRE
      INTEGER, INTENT(OUT)      :: IAT
      REAL(DOUBLE), INTENT(OUT) :: RECC
      END SUBROUTINE
      END INTERFACE
      END MODULE
