      MODULE recop2_I
      INTERFACE
!
      SUBROUTINE RECOP2(NS,JA1,JA2,K1,K2,KA,IRE,IAT,RECC)
      USE vast_kind_param,  ONLY:  DOUBLE
      INTEGER, INTENT(IN)       :: NS, JA1, JA2, K1, K2, KA, IRE
      INTEGER, INTENT(OUT)      :: IAT
      REAL(DOUBLE), INTENT(OUT) :: RECC
      END SUBROUTINE
      END INTERFACE
      END MODULE
