      MODULE recoonescalar_I
      INTERFACE
!
      SUBROUTINE RECOONESCALAR(NS,JA1,JA2,JA3,JA4,KA,IAT)
      INTEGER, INTENT(IN)  :: NS, JA1, JA2, JA3, JA4, KA
      INTEGER, INTENT(OUT) :: IAT
      END SUBROUTINE
      END INTERFACE
      END MODULE
