      MODULE rkco_GG_I
      INTERFACE
!
      SUBROUTINE RKCO_GG (JA,JB,CORD,INCOR,ICOLBREI)
!      USE vast_kind_param, ONLY:  DOUBLE
      EXTERNAL CORD
      INTEGER, INTENT(IN) :: JA,JB,INCOR,ICOLBREI
      END SUBROUTINE
      END INTERFACE
      END MODULE
