      MODULE rumtjj_I
      INTERFACE
!
      SUBROUTINE RUMTJJ(KNT,JJ,LQ,LV,L)
      INTEGER, INTENT(IN)  :: JJ, KNT
      INTEGER, INTENT(OUT) :: LQ, LV, L
      END SUBROUTINE
      END INTERFACE
      END MODULE
