      MODULE rwjj_I
      INTERFACE
!
      SUBROUTINE RWJJ(J,J1,J2,K1,K2,COEF)
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER,      INTENT(IN)  :: J, J1, J2, K1, K2
      REAL(DOUBLE), INTENT(OUT) :: COEF
      END SUBROUTINE
      END INTERFACE
      END MODULE
