      MODULE sixj35_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90 4.3E  10:06:26  11/16/01
      SUBROUTINE sixj35 (J, K, L, M, N, ITIK, SI)
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER, INTENT(IN) :: J
      INTEGER, INTENT(IN) :: K
      INTEGER, INTENT(IN) :: L
      INTEGER, INTENT(IN) :: M
      INTEGER, INTENT(IN) :: N
      INTEGER, INTENT(IN) :: ITIK
      REAL(DOUBLE), INTENT(OUT) :: SI
!VAST.../CONSTS/ ZERO(IN), ONE(IN), TWO(IN), THREE(IN), FOUR(IN)
!VAST...Calls: IXJTIK
      END SUBROUTINE
      END INTERFACE
      END MODULE
