      MODULE snrc_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE snrc (IS, KAPS, KS, ND1, ND2, NE1, NE2, IBRD, IBRE)
      INTEGER, DIMENSION(4), INTENT(IN) :: IS
      INTEGER, DIMENSION(4), INTENT(IN) :: KAPS
      INTEGER, DIMENSION(4), INTENT(IN) :: KS
      INTEGER, INTENT(OUT) :: ND1
      INTEGER, INTENT(OUT) :: ND2
      INTEGER, INTENT(OUT) :: NE1
      INTEGER, INTENT(OUT) :: NE2
      INTEGER, INTENT(OUT) :: IBRD
      INTEGER, INTENT(OUT) :: IBRE
      END SUBROUTINE
      END INTERFACE
      END MODULE
