      MODULE SUWJJ_I
      INTERFACE
!
      SUBROUTINE SUWJJ(K1,K2,LL,J1,J2,SUW)
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER,      INTENT(IN)  :: K1, K2, J1, J2
      INTEGER,      INTENT(OUT) :: LL
      REAL(DOUBLE), INTENT(OUT) :: SUW
      END SUBROUTINE
      END INTERFACE
      END MODULE
