      MODULE setmcp2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  11:01:42   1/ 5/07  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setmcp2 (MYID, NPROCS, NCORE, IDBLK, FILEHEAD) 
      INTEGER, INTENT(IN) :: MYID 
      INTEGER :: NPROCS 
      INTEGER :: NCORE 
      CHARACTER (LEN = 8), DIMENSION(*) :: IDBLK 
      CHARACTER (LEN = *) :: FILEHEAD 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
