      MODULE sortmem_I   
      INTERFACE
      SUBROUTINE sortmem (NFILE,IGGMAX_K,NCOEFF,NTGRAL,LPRINT,NB,FHEAD)
      INTEGER, INTENT(IN)  :: NFILE 
      INTEGER, INTENT(IN)  :: NCOEFF 
      INTEGER, INTENT(OUT) :: NTGRAL 
      LOGICAL, INTENT(IN)  :: LPRINT 
      INTEGER, INTENT(IN)  :: NB,IGGMAX_K
      CHARACTER (LEN = *), INTENT(IN) :: FHEAD 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
