      MODULE estrms_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:42:40   1/ 2/07
      REAL(KIND(0.0D0)) FUNCTION estrms (APARM, CPARM)
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE), INTENT(IN) :: APARM
      REAL(DOUBLE), INTENT(IN) :: CPARM
      END FUNCTION
      END INTERFACE
      END MODULE
