      MODULE getcpr_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:42:40   1/ 2/07  
      SUBROUTINE getcpr (RRMS, APARM, CPARM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: RRMS 
      REAL(DOUBLE) :: APARM 
      REAL(DOUBLE), INTENT(OUT) :: CPARM 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
