      MODULE skfun_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:42:40   1/ 2/07
      REAL(KIND(0.0D0)) FUNCTION skfun (K, X)
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER, INTENT(IN) :: K
      REAL(DOUBLE), INTENT(IN) :: X
      END FUNCTION
      END INTERFACE
      END MODULE
