      MODULE hmout_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE hmout (MYID, NPROCS, NCF) 
      INTEGER :: MYID 
!VAST...Dummy argument MYID is not referenced in this routine.
      INTEGER :: NPROCS 
!VAST...Dummy argument NPROCS is not referenced in this routine.
      INTEGER, INTENT(IN) :: NCF 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
