      MODULE maneig_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  16:49:56   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE maneig (dvdfirst,LPRINT, JBLOCK, NCFPAT, NCMINPAT, NEVECPAT, NCFTOT)
      logical, INTENT(IN) ::  dvdfirst
      LOGICAL :: LPRINT
!VAST...Dummy argument LPRINT is not referenced in this routine.
      INTEGER, INTENT(IN) :: JBLOCK
      INTEGER, INTENT(IN) :: NCFPAT
      INTEGER, INTENT(IN) :: NCMINPAT
      INTEGER, INTENT(IN) :: NEVECPAT
      INTEGER :: NCFTOT
      END SUBROUTINE
      END INTERFACE
      END MODULE
