      MODULE orthy_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  16:57:18   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE orthy (NW, JP, LSORT)
      INTEGER, INTENT(IN) :: NW
      INTEGER, INTENT(IN) :: JP
      LOGICAL, INTENT(IN) :: LSORT
      END SUBROUTINE
      END INTERFACE
      END MODULE
