      MODULE outbnd_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      LOGICAL FUNCTION outbnd (ETRY)
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE), INTENT(IN) :: ETRY
      END FUNCTION
      END INTERFACE
      END MODULE
