      MODULE solve_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:37:37  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE solve (J, FAIL, INV, JP, NNP)
      INTEGER, INTENT(IN) :: J
      LOGICAL, INTENT(OUT) :: FAIL
      INTEGER, INTENT(OUT) :: INV
      INTEGER, INTENT(IN) :: JP
      INTEGER, INTENT(IN) :: NNP
      END SUBROUTINE
      END INTERFACE
      END MODULE
