      MODULE alclla_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:22:09  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE ALCLLA(IBEG, ILAB, ILAST, ILEFT, IPTCS, IRIGH, LBLIN, &
         LLDIM, IMODE)
      INTEGER, INTENT(INOUT) :: LLDIM 
      INTEGER, INTENT(IN) :: IMODE 
      INTEGER, DIMENSION(:), pointer :: IBEG, ILAB, ILAST, ILEFT, &
                                        IPTCS, IRIGH, LBLIN
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
