      MODULE alcnsa_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:22:09  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE ALCNSA(JJA, JJB, HB1, HB2, HC1, HC2, HM1, &
          HM2, LAB, NPTR, NSDIM, IMODE) 
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER  :: NSDIM 
      INTEGER, INTENT(IN) :: IMODE 
      INTEGER, DIMENSION(:), pointer :: JJA, JJB, LAB, NPTR
      REAL(DOUBLE), DIMENSION(:), POINTER :: HB1, HB2, HC1, HC2, HM1, HM2
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
