      MODULE alcnta_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:22:09  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE ALCNTA(ISLDR, ISLDR1, XSLDR, NTDIM, IMODE)
      USE vast_kind_param, ONLY:  DOUBLE 
      INTEGER, DIMENSION(:), POINTER :: ISLDR, ISLDR1
      REAL(DOUBLE), DIMENSION(:), POINTER :: XSLDR
      INTEGER, INTENT(INOUT) :: NTDIM 
      INTEGER, INTENT(IN) :: IMODE 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
