      MODULE trsort_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  07:53:13   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE trsort (NAME, NFILE, NFILE2, LPRINT, JKP, IBLKI, IBLKF)
      CHARACTER (LEN = 24), DIMENSION(2), INTENT(IN) :: NAME
      INTEGER, INTENT(IN) :: NFILE
      INTEGER, INTENT(IN) :: NFILE2
      LOGICAL, INTENT(IN) :: LPRINT
      INTEGER :: JKP
      INTEGER, INTENT(IN) :: IBLKI
      INTEGER, INTENT(IN) :: IBLKF
      END SUBROUTINE
      END INTERFACE
      END MODULE
