      MODULE alcbuf_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  16:02:30   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE alcbuf (MODE)
      INTEGER, INTENT(IN) :: MODE
!VAST...Calls: ALLOC, RALLOC, DALLOC
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
