      MODULE arctan_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:46:34   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      REAL(KIND(0.0D0)) FUNCTION arctan (ARG1, ARG2) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: ARG1 
      REAL(DOUBLE), INTENT(IN) :: ARG2 
!VAST.../DEF9/ PI(IN)
      END FUNCTION  
      END INTERFACE 
      END MODULE 
