      MODULE calen_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:46:38   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE calen (JTIME, JDATE)
      CHARACTER(LEN=10)  :: JTIME
      CHARACTER(LEN=8)  :: JDATE
      END SUBROUTINE
      END INTERFACE
      END MODULE
