      MODULE clrx_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:46:52   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      REAL(KIND(0.0D0)) FUNCTION clrx (KAPPAA, K, KAPPAB)
      INTEGER MFACT
      PARAMETER(MFACT=500)
      INTEGER, INTENT(IN) :: KAPPAA
      INTEGER, INTENT(IN) :: K
      INTEGER, INTENT(IN) :: KAPPAB
!VAST.../FACTS/ GAM(IN)
      END FUNCTION
      END INTERFACE
      END MODULE
