      MODULE convrt2_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:46:54   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE convrt2 (INTNUM, CNUM, LENTH, FROM)
      INTEGER, INTENT(IN) :: INTNUM
      CHARACTER (LEN = *), INTENT(INOUT) :: CNUM
      INTEGER, INTENT(OUT) :: LENTH
      CHARACTER (LEN = *), INTENT(IN) :: FROM
!VAST.../IOUNIT/ ISTDE(IN)
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
