      MODULE cord_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:46:57   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE cord (JA, JB, JA1, IPCA, JB1)
      INTEGER :: JA
      INTEGER :: JB
      INTEGER, INTENT(IN) :: JA1
      INTEGER, INTENT(IN) :: IPCA
      INTEGER, INTENT(IN) :: JB1
!VAST.../ORB4/ NAK(IN)
!VAST.../M1/ NQ1(IN)
!VAST.../M3/ JLIST(IN), KLIST(IN)
!VAST...Calls: SPEAK, CLRX
      END SUBROUTINE
      END INTERFACE
      END MODULE
