      MODULE cre_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:10   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      REAL(KIND(0.0D0)) FUNCTION cre (KAP1, K, KAP2)
      INTEGER, INTENT(IN) :: KAP1
      INTEGER :: K
      INTEGER, INTENT(IN) :: KAP2
!VAST...Calls: CLRX
      END FUNCTION
      END INTERFACE
      END MODULE
