      MODULE cslh_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:12   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE cslh (NAME, NCORE, NBLKIN, IDBLK) 
      CHARACTER (LEN = *) :: NAME 
      INTEGER :: NCORE 
      INTEGER, INTENT(IN) :: NBLKIN 
      CHARACTER (LEN = 8), DIMENSION(*) :: IDBLK 
!VAST.../HBLOCK/ NBLOCK(INOUT), PNCFBLK(INOUT)
!VAST.../ORB2/ NCFTOT(INOUT)
!VAST...Calls: ALLOC, SETCSLL, NCFBLK, RALLOC, LODCSH
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
