      MODULE dcbsrw_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:15   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE dcbsrw (N, KAPPA, Z, E, RG0, RG, RF, MTP) 
      USE vast_kind_param,ONLY: DOUBLE 
      USE parameter_def, ONLY: NNNP
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: KAPPA 
      REAL(DOUBLE), INTENT(IN) :: Z 
      REAL(DOUBLE), INTENT(OUT) :: E 
      REAL(DOUBLE), INTENT(OUT) :: RG0 
      REAL(DOUBLE), DIMENSION(NNNP), INTENT(INOUT) :: RG 
      REAL(DOUBLE), DIMENSION(NNNP), INTENT(OUT) :: RF 
      INTEGER, INTENT(OUT) :: MTP 
!VAST.../DEF2/ C(IN)
!VAST.../DEF4/ ACCY(IN)
!VAST.../GRID/ R(IN), NTP(IN)
!VAST.../TATB/ TA(INOUT), TB(INOUT)
!VAST...Calls: CGAMMA
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
