      MODULE dinit_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:18   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE dinit (N, A, X, INCX)
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER, INTENT(IN) :: N
      REAL(DOUBLE), INTENT(IN) :: A
      REAL(DOUBLE), DIMENSION(*), INTENT(OUT) :: X
      INTEGER, INTENT(IN) :: INCX
      END SUBROUTINE
      END INTERFACE
      END MODULE
