      MODULE dmerge_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:20   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE dmerge (N, DB, DC, IDY, DA, DCONST, DL)
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER, INTENT(IN) :: N
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: DB
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: DC
      INTEGER, DIMENSION(N), INTENT(IN) :: IDY
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: DA
      REAL(DOUBLE), INTENT(IN) :: DCONST
      REAL(DOUBLE), INTENT(OUT) :: DL
      END SUBROUTINE
      END INTERFACE
      END MODULE
