      MODULE dpbdt_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:21   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE dpbdt (J) 
      INTEGER :: J 
!VAST.../GRID/ N(IN)
!VAST.../LIC13/ A(IN)
!VAST.../TATB/ TA(OUT), TB(OUT)
!VAST...Calls: PF, QF
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
