      MODULE draw_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:22   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE draw (P, SP, Q, SQ, MF) 
      USE vast_kind_param,ONLY: DOUBLE 
      USE parameter_def, ONLY: NNNP
      REAL(DOUBLE), DIMENSION(NNNP), INTENT(IN) :: P 
      REAL(DOUBLE), INTENT(IN) :: SP 
      REAL(DOUBLE), DIMENSION(NNNP), INTENT(IN) :: Q 
      REAL(DOUBLE), INTENT(IN) :: SQ 
      INTEGER, INTENT(IN) :: MF 
!VAST.../GRID/ R(IN), N(IN)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
