      MODULE es_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:25   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE es (F, S2F, S3F)
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE), INTENT(IN) :: F
      REAL(DOUBLE), INTENT(OUT) :: S2F
      REAL(DOUBLE), INTENT(OUT) :: S3F
      END SUBROUTINE
      END INTERFACE
      END MODULE
