      MODULE getrsl_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:14   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE getrsl (INDX, NSUBS)
      INTEGER, DIMENSION(*), INTENT(INOUT) :: INDX
      INTEGER, INTENT(OUT) :: NSUBS
!VAST.../ORB2/ NW(IN)
!VAST.../ORB4/ NP(IN)
!VAST.../ORB10/ NH(IN)
!VAST.../IOUNIT/ ISTDE(IN)
!VAST...Calls: LDIGIT, CONVRT
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
