      MODULE ichkq1_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:20   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      INTEGER FUNCTION ichkq1 (JA, JB)
      INTEGER :: JA
      INTEGER :: JB
!VAST.../ORB2/ NW(IN)
!VAST...Calls: IQ
      END FUNCTION
      END INTERFACE
      END MODULE
