      MODULE ichop_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:25   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      INTEGER FUNCTION ichop (ISUBSH, ICSF)
      INTEGER, INTENT(IN) :: ISUBSH
      INTEGER :: ICSF
      END FUNCTION
      END INTERFACE
      END MODULE
