      MODULE icopy_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:29   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE icopy (N, IX, INCX, IY, INCY)
      INTEGER, INTENT(IN) :: N
      INTEGER, DIMENSION(*), INTENT(IN) :: IX
      INTEGER :: INCX
!VAST...Dummy argument INCX is not referenced in this routine.
      INTEGER, DIMENSION(*), INTENT(OUT) :: IY
      INTEGER :: INCY
!VAST...Dummy argument INCY is not referenced in this routine.
      END SUBROUTINE
      END INTERFACE
      END MODULE
