      MODULE iniest2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:36:59   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE iniest2 (NMAX, NCF, NIV, BASIS, HMX, JCOL, IROW) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NMAX 
      INTEGER, INTENT(IN) :: NCF 
      INTEGER, INTENT(IN) :: NIV 
      REAL(DOUBLE), DIMENSION(*) :: BASIS 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: HMX 
      INTEGER, DIMENSION(0:*), INTENT(IN) :: JCOL 
      INTEGER, DIMENSION(*), INTENT(IN) :: IROW 
!VAST...Calls: ALLOC, DINIT, DSPEVX, DCOPY, DALLOC
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
