      MODULE intrpq_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  15:33:45   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE intrpq (PA, QA, MA, RA, J, DNORM)
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER MXORD
      PARAMETER (MXORD = 13)
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: PA, QA, RA
      INTEGER, INTENT(IN) :: MA
      INTEGER, INTENT(IN) :: J
      REAL(DOUBLE), INTENT(OUT) :: DNORM
      END SUBROUTINE
      END INTERFACE
      END MODULE
