      MODULE ispar_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:41   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      INTEGER FUNCTION ispar (ICSF)
      INTEGER, INTENT(IN) :: ICSF
!VAST.../ORB2/ NCF(IN)
!VAST.../IOUNIT/ ISTDE(IN)
!VAST...Calls: JCUPA
!...This routine performs I/O.
      END FUNCTION
      END INTERFACE
      END MODULE
