      MODULE itrig_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:47   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      INTEGER FUNCTION itrig (I1, I2, I3)
      INTEGER, INTENT(IN) :: I1
      INTEGER, INTENT(IN) :: I2
      INTEGER, INTENT(IN) :: I3
      END FUNCTION
      END INTERFACE
      END MODULE
