      MODULE jcup_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  08:16:51   2/21/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      INTEGER FUNCTION jcup (LOC, ICSF)
      INTEGER, INTENT(IN) :: LOC
      INTEGER, INTENT(IN) :: ICSF
!VAST.../ORB2/ NCF(IN), NW(IN)
!VAST.../IOUNIT/ ISTDE(IN)
!VAST...Calls: JCUPA
!...This routine performs I/O.
      END FUNCTION
      END INTERFACE
      END MODULE
