      MODULE jqs_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:50   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      INTEGER FUNCTION jqs (IWHICH, ISUBSH, ICSF)
      INTEGER :: IWHICH
      INTEGER, INTENT(IN) :: ISUBSH
      INTEGER :: ICSF
!VAST...Calls: JQSA
      END FUNCTION
      END INTERFACE
      END MODULE
