      MODULE ldigit_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:52   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      LOGICAL FUNCTION ldigit (CST)
      CHARACTER (LEN = 1), INTENT(IN) :: CST
      END FUNCTION
      END INTERFACE
      END MODULE
