      MODULE lodiso_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:49:53   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE lodiso 
!VAST.../DEF1/ EMN(OUT), Z(INOUT)
!VAST.../DEF11/ FMTOAU(IN), AUMAMU(IN)
!VAST.../NPAR/ PARM(OUT), NPARM(OUT)
!VAST.../NSMDAT/ SQN(INOUT), DMOMNM(INOUT), QMOMB(INOUT)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
