      MODULE lodstate_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:49:58   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE LODSTATE(IDBLK)
      CHARACTER (LEN = 8), DIMENSION(*) :: IDBLK
!VAST.../DEF7/ PCCMIN(INOUT), NCMIN(OUT)
!VAST.../IOUNIT/ ISTDE(IN)
!VAST...Calls: ITEMS, DALLOC, ICCMIN
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
