      MODULE ltab_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:49:59   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE ltab (IS, NQS, KS, IROWS)
      INTEGER, DIMENSION(4), INTENT(IN) :: IS
      INTEGER, DIMENSION(4), INTENT(INOUT) :: NQS
      INTEGER, DIMENSION(4), INTENT(IN) :: KS
      INTEGER, DIMENSION(4), INTENT(INOUT) :: IROWS
!VAST.../TERMS/ NROWS(IN)
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
