      MODULE openfl_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:04   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE openfl (NFILE, FILNAM, RFORM, RSTAT, IERR)
      INTEGER, INTENT(IN) :: NFILE
      CHARACTER (LEN = *), INTENT(IN) :: FILNAM
      CHARACTER (LEN = *), INTENT(IN) :: RFORM
      CHARACTER (LEN = *), INTENT(IN) :: RSTAT
      INTEGER, INTENT(OUT) :: IERR
!VAST.../IOUNIT/ ISTDE(IN)
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
