      MODULE orthsc_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  15:41:29   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE orthsc
!VAST.../DEBUGR/ LDBPR(IN)
!VAST.../DEF4/ ACCY(IN)
!VAST.../ORB2/ NW(IN)
!VAST.../ORB4/ NP(IN), NAK(IN)
!VAST.../ORB10/ NH(IN)
!VAST.../WAVE/ PZ(INOUT), MF(INOUT)
!VAST...Calls: RINT
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
