      MODULE posfile_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:12   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE posfile (MODE, NUNIT, NREC) 
      INTEGER, INTENT(IN) :: MODE 
      INTEGER, INTENT(IN) :: NUNIT 
      INTEGER, INTENT(IN) :: NREC 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
