      MODULE prsrcn_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:15   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE prsrcn (RECORD, NCORE, IOCCS, IERR)
      USE parameter_def, ONLY: NNNW
      CHARACTER (LEN = 256), INTENT(IN) :: RECORD
      INTEGER, INTENT(IN) :: NCORE
      INTEGER, DIMENSION(NNNW), INTENT(OUT) :: IOCCS
      INTEGER, INTENT(OUT) :: IERR
!VAST.../ORB2/ NW(IN)
!VAST.../ORB4/ NP(IN)
!VAST.../ORB5/ NKJ(IN)
!VAST.../ORB10/ NH(IN)
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
