      MODULE quad_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:18   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE quad (RESULT)
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE), INTENT(OUT) :: RESULT
!VAST.../GRID/ R(IN), RP(IN)
!VAST.../NCC/ C1(IN), C2(IN), C3(IN), C4(IN)
!VAST.../TATB/ TA(INOUT), MTP(IN)
      END SUBROUTINE
      END INTERFACE
      END MODULE
