      MODULE rint_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:22   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      REAL(KIND(0.0D0)) FUNCTION rint (I, J, K) 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(IN) :: J 
      INTEGER, INTENT(IN) :: K 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
