      MODULE setcsh_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:30   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setcsh (NFILE, NAME, NCORE)
      INTEGER, INTENT(IN) :: NFILE
      CHARACTER (LEN = *), INTENT(IN) :: NAME
      INTEGER :: NCORE
!VAST.../IOUNIT/ ISTDE(IN)
!VAST...Calls: LODCSH
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
