      MODULE setcsla_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:33   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setcsla (NAME, NCORE) 
      CHARACTER (LEN = 24), INTENT(IN) :: NAME 
      INTEGER :: NCORE 
!VAST.../IOUNIT/ ISTDE(IN)
!VAST...Calls: OPENFL, LODCSL
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
