      MODULE setiso_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:35   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setiso (FNAME) 
      CHARACTER (LEN = *), INTENT(IN) :: FNAME 
!VAST.../IOUNIT/ ISTDE(IN)
!VAST...Calls: OPENFL, LODISO
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
