      MODULE setmc_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:37   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setmc
!VAST.../DEBUGG/ LDBPG(IN)
!VAST.../DEF0/ TENMAX(OUT), EXPMAX(OUT), EXPMIN(OUT), PRECIS(OUT)
!VAST...Calls: DLAMCH
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
