      MODULE setpot_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:38   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setpot (J, JP) 
      INTEGER, INTENT(IN) :: J 
      INTEGER, INTENT(OUT) :: JP 
!VAST.../IOUNIT/ ISTDE(IN)
!VAST.../DEF2/ C(IN)
!VAST.../DEF4/ ACCY(IN)
!VAST.../GRID/ RP(IN), RPOR(IN), H(IN), N(IN)
!VAST.../INT3/ TF(OUT), TG(INOUT)
!VAST.../ORB1/ E(IN)
!VAST.../POTE/ YP(IN)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
