      MODULE setqna_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:39   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setqna (JA, JB)
      INTEGER :: JA
      INTEGER :: JB
!VAST.../M0/ JJC1(INOUT), JJC2(INOUT)
!VAST.../M1/ NQ1(OUT), NQ2(OUT)
!VAST.../M2/ JJQ1(OUT), JJQ2(OUT)
!VAST.../M3/ JLIST(INOUT), KLIST(OUT), NPEEL(OUT), NCORE(OUT)
!VAST.../ORB2/ NW(IN)
!VAST...Calls: IQ, JQS, ICHOP, JCUP
      END SUBROUTINE
      END INTERFACE
      END MODULE
