      MODULE setrwfa_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:42   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE setrwfa (NAME) 
      CHARACTER (LEN = *), INTENT(IN) :: NAME 
!VAST.../IOUNIT/ ISTDE(IN)
!VAST...Calls: OPENFL, LODRWF
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
