      MODULE skrc_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:43   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE skrc (IS, KAPS, KS, KD1, KD2, KE1, KE2)
      INTEGER, DIMENSION(4), INTENT(IN) :: IS
      INTEGER, DIMENSION(4), INTENT(IN) :: KAPS
      INTEGER, DIMENSION(4), INTENT(IN) :: KS
      INTEGER, INTENT(OUT) :: KD1
      INTEGER, INTENT(OUT) :: KD2
      INTEGER, INTENT(OUT) :: KE1
      INTEGER, INTENT(OUT) :: KE2
      END SUBROUTINE
      END INTERFACE
      END MODULE
