      MODULE starttime_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:49   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE starttime (NCOUNT1, PROGNAME)
      INTEGER :: NCOUNT1
      CHARACTER (LEN = *), INTENT(IN) :: PROGNAME
!VAST...Calls: DATE_AND_TIME, SYSTEM_CLOCK
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
