      MODULE stoptime_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:50   2/14/04  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE stoptime (NCOUNT1, PROGNAME) 
      INTEGER, INTENT(IN) :: NCOUNT1 
      CHARACTER (LEN = *), INTENT(IN) :: PROGNAME 
!VAST...Calls: SYSTEM_CLOCK, DATE_AND_TIME
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
