      MODULE frmtfp_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  11:02:52   1/ 2/07
      SUBROUTINE frmtfp (INDEX, NSUBS)
      INTEGER NNNW
      PARAMETER (NNNW = 120)
      INTEGER, DIMENSION(NNNW), INTENT(IN) :: INDEX
      INTEGER, INTENT(IN) :: NSUBS
      END SUBROUTINE
      END INTERFACE
      END MODULE
