      MODULE screenpar_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  11:02:52   1/ 2/07
      SUBROUTINE screenpar (NCORE)
      INTEGER NNNW
      PARAMETER (NNNW = 120)
      INTEGER, INTENT(IN) :: NCORE
      END SUBROUTINE
      END INTERFACE
      END MODULE
