      MODULE solvh_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  11:06:08   1/ 2/07
      SUBROUTINE solvh (IORB, FAIL)
      INTEGER NNNP
      PARAMETER (NNNP = 590)
      INTEGER NNN1
      PARAMETER (NNN1 = 600)
      INTEGER NNNW
      PARAMETER (NNNW = 120)
      INTEGER, INTENT(IN) :: IORB
      LOGICAL, INTENT(OUT) :: FAIL
      END SUBROUTINE
      END INTERFACE
      END MODULE
