      MODULE summry_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  11:02:52   1/ 2/07
      SUBROUTINE summry (NUNIT)
      INTEGER NNN1
      PARAMETER (NNN1 = 600)
      INTEGER NNNW
      PARAMETER (NNNW = 120)
      INTEGER, INTENT(IN) :: NUNIT
      END SUBROUTINE
      END INTERFACE
      END MODULE
