name: Verify build files

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Verify CMake/Make files
      run: ./contrib/genbuildall.sh --verify
