name: Verify build files

# branches: '*' only matches "main" branches, i.e. ones without a /
# This ensures that we don't run CI multiple times on pull requests, since we expect all
# feature branches to be namespaced as <prefix>/<branch>.
on:
  push:
    branches: '*'
    tags: '**'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Verify CMake/Make files
      run: ./contrib/genbuildall.sh --verify
