      MODULE alcnma_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:22:09  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
     SUBROUTINE ALCNMA(IPTR, ISLDR, ISLDR1, XSLDR, NMDIM, IMODE)
      USE vast_kind_param, ONLY:  DOUBLE
      INTEGER, DIMENSION(:), pointer :: IPTR, ISLDR, ISLDR1
      REAL(DOUBLE), DIMENSION(:), pointer :: XSLDR
      INTEGER, INTENT(INOUT) :: NMDIM
      INTEGER, INTENT(IN) :: IMODE
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
