      MODULE cpmix_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:22:09  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE cpmix (NAME, INPCI)
      CHARACTER (LEN = 128), DIMENSION(2), INTENT(INOUT) :: NAME
      INTEGER, INTENT(IN) :: INPCI
      END SUBROUTINE
      END INTERFACE
      END MODULE
