      MODULE fname_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:22:09  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE fname (NAME) 
      CHARACTER (LEN = 24), DIMENSION(2), INTENT(IN) :: NAME 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
