      MODULE jcupr_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:22:09  12/28/06  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      INTEGER FUNCTION jcupr (LOC, ICSF) 
      INTEGER, INTENT(IN) :: LOC 
      INTEGER, INTENT(IN) :: ICSF 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
