      MODULE lodrwfi_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  07:25:11   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE lodrwfi (NAME)
      CHARACTER (LEN = 128), INTENT(IN) :: NAME
      END SUBROUTINE
      END INTERFACE
      END MODULE
