      MODULE mctin_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  07:26:50   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE mctin (IOPAR, JKP, NAME)
      INTEGER :: IOPAR
!VAST...Dummy argument IOPAR is not referenced in this routine.
      INTEGER, INTENT(IN) :: JKP
      CHARACTER (LEN = 24), DIMENSION(2) :: NAME
      END SUBROUTINE
      END INTERFACE
      END MODULE
