      MODULE readmix_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:04:38   1/ 6/07  
!...Modified by Charlotte Froese Fischer 
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE readmix (NAME, INPCI, INIT) 
      CHARACTER (LEN = 24), DIMENSION(2) :: NAME 
      INTEGER :: INPCI 
      INTEGER, INTENT(IN) :: INIT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
